### ISSUE TITLE
Error generating reads

### ISSUE THREAD

**Issue by slvrshot** [meren/reads-for-assembly#4]
Hi again - I have some bacterial assemblies that were originally sequenced in another country and I am trying to use your tool. It appears all of the assemblies in my folder generate this error. I have attached an assembly for you to inspect.

ini file settings
 [general]
output_sample_name = test
insert_size = 30
insert_size_std = 1
short_read_length = 250
error_rate = 0.01

```
Traceback (most recent call last):
  File "./gen-paired-end-reads", line 15, in <module>
    p.generate()
  File "/scicomp/groups/OID/NCHHSTP/DSTDB/LRRB/CRO_AZI_DataProcessing/reads-for-assembly-master/reads_for_assembly/generators.py", line 127, in generate
    start_pos = random.randint(0, L - (x * 2))
  File "/apps/x86_64/python/3.8.3/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/apps/x86_64/python/3.8.3/lib/python3.8/random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0, -57, -57)

```
[395-12.zip](https://github.com/merenlab/reads-for-assembly/files/4740529/395-12.zip)

**Comment by meren** [comment]
Hey @slvrshot,

Thanks for reporting this. I realized your FASTA file included many reads that were way too short to generate "short reads" from given the minimum short-read length and insert size you've set in your config file.

If you pull from `master` you will see that the new code tells you what should be the minimum sequence length in your input FASTA file.

When I removed those sequences from 395-12.fasta, everything worked :)


Best,
